/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lendingPlatformSol from './LendingPlatform.sol/index.js';
export type { lendingPlatformSol };
import type * as loanStorageSol from './LoanStorage.sol/index.js';
export type { loanStorageSol };
import type * as tokenNftSol from './TokenNFT.sol/index.js';
export type { tokenNftSol };
export * as factories from './factories/index.js';
export type { LendingPlatform } from './LendingPlatform.sol/LendingPlatform.js';
export { LendingPlatform__factory } from './factories/LendingPlatform.sol/LendingPlatform__factory.js';
export type { LoanStorage } from './LoanStorage.sol/LoanStorage.js';
export { LoanStorage__factory } from './factories/LoanStorage.sol/LoanStorage__factory.js';
export type { TokenNFT } from './TokenNFT.sol/TokenNFT.js';
export { TokenNFT__factory } from './factories/TokenNFT.sol/TokenNFT__factory.js';