/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as lendingPlatformSol from './LendingPlatform.sol/index.js';
export * as loanStorageSol from './LoanStorage.sol/index.js';
export * as tokenNftSol from './TokenNFT.sol/index.js';