/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { LoanStorage, LoanStorageInterface } from "../../LoanStorage.sol/LoanStorage.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getTotalLoans",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getTotalRequests",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600f57600080fd5b50608a8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063833be5d5146037578063f0e22d5214604d575b600080fd5b6003545b60405190815260200160405180910390f35b600254603b56fea26469706673582212208b5dd69ff4f5cd577af6272b7d9e9c3a3d8f36a1ff52d2b10a4f2cf0cc67163f64736f6c63430008110033";

  
      type LoanStorageConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LoanStorageConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LoanStorage__factory extends ContractFactory {
    
      constructor(...args: LoanStorageConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LoanStorage & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LoanStorage__factory {
      return super.connect(runner) as LoanStorage__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LoanStorageInterface {
      return new Interface(_abi) as LoanStorageInterface;
    }
    
    override attach(address: string | Addressable): LoanStorage {
      return super.attach(address) as LoanStorage;
    }
  static connect(address: string, runner?: ContractRunner | null): LoanStorage {
      return new Contract(address, _abi, runner) as unknown as LoanStorage;
    }
  }

  
  