/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace LoanTypes {
      
    export type ActiveLoanStruct = {borrower: AddressLike, lender: AddressLike, loanAmount: BigNumberish, collateralTokenId: BigNumberish, startTimestamp: BigNumberish, endTime: BigNumberish, interestRate: BigNumberish, isRepaid: boolean}

    export type ActiveLoanStructOutput = [borrower: string, lender: string, loanAmount: bigint, collateralTokenId: bigint, startTimestamp: bigint, endTime: bigint, interestRate: bigint, isRepaid: boolean] & {borrower: string, lender: string, loanAmount: bigint, collateralTokenId: bigint, startTimestamp: bigint, endTime: bigint, interestRate: bigint, isRepaid: boolean }
  

    export type LoanRequestStruct = {borrower: AddressLike, loanAmount: BigNumberish, duration: BigNumberish, interestRate: BigNumberish, isActive: boolean, collateralTokenId: BigNumberish}

    export type LoanRequestStructOutput = [borrower: string, loanAmount: bigint, duration: bigint, interestRate: bigint, isActive: boolean, collateralTokenId: bigint] & {borrower: string, loanAmount: bigint, duration: bigint, interestRate: bigint, isActive: boolean, collateralTokenId: bigint }
  
    }

  export interface LendingPlatformInterface extends Interface {
    getFunction(nameOrSignature: "MAX_INTEREST_RATE" | "cancelLoanRequest" | "checkLoanStatus" | "collateralNft" | "createLoanRequest" | "fundLoanRequest" | "getAllActive" | "getBorrowerRequests" | "getRepayAmount" | "getTotalLoans" | "getTotalRequests" | "liquidateExpiredLoan" | "repayLoan"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LoanFunded" | "LoanLiquidated" | "LoanRepaid" | "LoanRequestCancelled" | "LoanRequestCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_INTEREST_RATE', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelLoanRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'checkLoanStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'collateralNft', values?: undefined): string;
encodeFunctionData(functionFragment: 'createLoanRequest', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundLoanRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBorrowerRequests', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRepayAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTotalLoans', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalRequests', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidateExpiredLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'repayLoan', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MAX_INTEREST_RATE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelLoanRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkLoanStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collateralNft', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLoanRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundLoanRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrowerRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRepayAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidateExpiredLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayLoan', data: BytesLike): Result;
  }

  
    export namespace LoanFundedEvent {
      export type InputTuple = [loanId: BigNumberish, requestId: BigNumberish, lender: AddressLike, borrower: AddressLike, loanAmount: BigNumberish, collateralTokenId: BigNumberish];
      export type OutputTuple = [loanId: bigint, requestId: bigint, lender: string, borrower: string, loanAmount: bigint, collateralTokenId: bigint];
      export interface OutputObject {loanId: bigint, requestId: bigint, lender: string, borrower: string, loanAmount: bigint, collateralTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanLiquidatedEvent {
      export type InputTuple = [loanId: BigNumberish, lender: AddressLike, collateralTokenId: BigNumberish];
      export type OutputTuple = [loanId: bigint, lender: string, collateralTokenId: bigint];
      export interface OutputObject {loanId: bigint, lender: string, collateralTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRepaidEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, repayAmount: BigNumberish];
      export type OutputTuple = [loanId: bigint, borrower: string, lender: string, repayAmount: bigint];
      export interface OutputObject {loanId: bigint, borrower: string, lender: string, repayAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRequestCancelledEvent {
      export type InputTuple = [requestId: BigNumberish, borrower: AddressLike, collateralTokenId: BigNumberish];
      export type OutputTuple = [requestId: bigint, borrower: string, collateralTokenId: bigint];
      export interface OutputObject {requestId: bigint, borrower: string, collateralTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRequestCreatedEvent {
      export type InputTuple = [requestId: BigNumberish, borrower: AddressLike, loanAmount: BigNumberish, durationInDays: BigNumberish, interestRate: BigNumberish, collateralTokenId: BigNumberish];
      export type OutputTuple = [requestId: bigint, borrower: string, loanAmount: bigint, durationInDays: bigint, interestRate: bigint, collateralTokenId: bigint];
      export interface OutputObject {requestId: bigint, borrower: string, loanAmount: bigint, durationInDays: bigint, interestRate: bigint, collateralTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LendingPlatform extends BaseContract {
    
    connect(runner?: ContractRunner | null): LendingPlatform;
    waitForDeployment(): Promise<this>;

    interface: LendingPlatformInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_INTEREST_RATE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cancelLoanRequest: TypedContractMethod<
      [_requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    checkLoanStatus: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [[boolean, bigint, bigint, bigint, bigint, bigint, string, string] & {isClosed: boolean, loanAmount: bigint, startTimestamp: bigint, endTime: bigint, interestRate: bigint, collateralTokenId: bigint, borrower: string, lender: string }],
      'view'
    >
    

    
    collateralNft: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createLoanRequest: TypedContractMethod<
      [_loanAmount: BigNumberish, _durationInDays: BigNumberish, _interestRate: BigNumberish, _collateralTokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundLoanRequest: TypedContractMethod<
      [_requestId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getAllActive: TypedContractMethod<
      [],
      [[bigint[], LoanTypes.ActiveLoanStructOutput[], bigint[], LoanTypes.LoanRequestStructOutput[]] & {loanIds: bigint[], loans: LoanTypes.ActiveLoanStructOutput[], requestIds: bigint[], requests: LoanTypes.LoanRequestStructOutput[] }],
      'view'
    >
    

    
    getBorrowerRequests: TypedContractMethod<
      [_borrower: AddressLike, ],
      [[bigint[], LoanTypes.LoanRequestStructOutput[]] & {requestIds: bigint[], requests: LoanTypes.LoanRequestStructOutput[] }],
      'view'
    >
    

    
    getRepayAmount: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTotalLoans: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTotalRequests: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    liquidateExpiredLoan: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    repayLoan: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_INTEREST_RATE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelLoanRequest'): TypedContractMethod<
      [_requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkLoanStatus'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [[boolean, bigint, bigint, bigint, bigint, bigint, string, string] & {isClosed: boolean, loanAmount: bigint, startTimestamp: bigint, endTime: bigint, interestRate: bigint, collateralTokenId: bigint, borrower: string, lender: string }],
      'view'
    >;
getFunction(nameOrSignature: 'collateralNft'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createLoanRequest'): TypedContractMethod<
      [_loanAmount: BigNumberish, _durationInDays: BigNumberish, _interestRate: BigNumberish, _collateralTokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundLoanRequest'): TypedContractMethod<
      [_requestId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getAllActive'): TypedContractMethod<
      [],
      [[bigint[], LoanTypes.ActiveLoanStructOutput[], bigint[], LoanTypes.LoanRequestStructOutput[]] & {loanIds: bigint[], loans: LoanTypes.ActiveLoanStructOutput[], requestIds: bigint[], requests: LoanTypes.LoanRequestStructOutput[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getBorrowerRequests'): TypedContractMethod<
      [_borrower: AddressLike, ],
      [[bigint[], LoanTypes.LoanRequestStructOutput[]] & {requestIds: bigint[], requests: LoanTypes.LoanRequestStructOutput[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getRepayAmount'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalLoans'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalRequests'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'liquidateExpiredLoan'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repayLoan'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'payable'
    >;

    getEvent(key: 'LoanFunded'): TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
getEvent(key: 'LoanLiquidated'): TypedContractEvent<LoanLiquidatedEvent.InputTuple, LoanLiquidatedEvent.OutputTuple, LoanLiquidatedEvent.OutputObject>;
getEvent(key: 'LoanRepaid'): TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
getEvent(key: 'LoanRequestCancelled'): TypedContractEvent<LoanRequestCancelledEvent.InputTuple, LoanRequestCancelledEvent.OutputTuple, LoanRequestCancelledEvent.OutputObject>;
getEvent(key: 'LoanRequestCreated'): TypedContractEvent<LoanRequestCreatedEvent.InputTuple, LoanRequestCreatedEvent.OutputTuple, LoanRequestCreatedEvent.OutputObject>;

    filters: {
      
      'LoanFunded(uint256,uint256,address,address,uint256,uint256)': TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
      LoanFunded: TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
    

      'LoanLiquidated(uint256,address,uint256)': TypedContractEvent<LoanLiquidatedEvent.InputTuple, LoanLiquidatedEvent.OutputTuple, LoanLiquidatedEvent.OutputObject>;
      LoanLiquidated: TypedContractEvent<LoanLiquidatedEvent.InputTuple, LoanLiquidatedEvent.OutputTuple, LoanLiquidatedEvent.OutputObject>;
    

      'LoanRepaid(uint256,address,address,uint256)': TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
      LoanRepaid: TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
    

      'LoanRequestCancelled(uint256,address,uint256)': TypedContractEvent<LoanRequestCancelledEvent.InputTuple, LoanRequestCancelledEvent.OutputTuple, LoanRequestCancelledEvent.OutputObject>;
      LoanRequestCancelled: TypedContractEvent<LoanRequestCancelledEvent.InputTuple, LoanRequestCancelledEvent.OutputTuple, LoanRequestCancelledEvent.OutputObject>;
    

      'LoanRequestCreated(uint256,address,uint256,uint256,uint256,uint256)': TypedContractEvent<LoanRequestCreatedEvent.InputTuple, LoanRequestCreatedEvent.OutputTuple, LoanRequestCreatedEvent.OutputObject>;
      LoanRequestCreated: TypedContractEvent<LoanRequestCreatedEvent.InputTuple, LoanRequestCreatedEvent.OutputTuple, LoanRequestCreatedEvent.OutputObject>;
    
    };
  }